---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Delete Workload
Resources:
  DeleteWorkloadStepFunction:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: Delete-Workload-1
      DefinitionString: !Sub
        - |-
          {
            "Comment": "Delete workload workflow",
            "StartAt": "DeleteResource",
            "States": {
              "DeleteResource": {
                "Type": "Task",
                "Resource": "${DeleteResourceLambdaArn}",
                "End": true,
                "Retry": [{
                    "ErrorEquals": ["States.ALL"],
                    "IntervalSeconds": 1,
                    "MaxAttempts": 3,
                    "BackoffRate": 2
                  }]
              }
            }
          }
        - DeleteResourceLambdaArn: !GetAtt
            - DeleteResourceLambda
            - Arn
      RoleArn: !GetAtt
        - StepFunctionRole
        - Arn
  StepFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub 'states.${AWS::Region}.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: lambda
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource: '*'
