
name: Analyze with CodeGuru Reviewer

on: 
  - push
  - pull_request
  - workflow_dispatch


permissions:
    id-token: write
    contents: read 
    security-events: write 

jobs:
  CodeGuruReviewerScan:
    runs-on: ubuntu-latest
    steps: 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Region to access CodeGuru 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: ./gradlew jar

    - name: Run CodeGuru Reviewer
      id: codeguru
      uses: aws-actions/codeguru-reviewer@v1.1
      continue-on-error: false
      with:          
        s3_bucket: codeguru-reviewer-github-xxz-test
        build_path: ./build/libs

    - name: Store SARIF file
      if: steps.codeguru.outcome == 'success'
      uses: actions/upload-artifact@v2
      with:
        name: SARIF_recommendations
        path: ./codeguru-results.sarif.json

    - name: Upload review result
      if: steps.codeguru.outcome == 'success'
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
